name: Build Windows release

on:
  push:
    tags: ["v.*"]

jobs:
  build-windows-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0

    - name: Set version in pyproject.toml and environment
      run: |
        set -x
        version=$(
            git describe --tags --dirty \
            | sed -e 's/^v//' -e 's/\([^-]*-g\)/dev\1/;s/-g.*//g'
          )
        echo "PAPIS_VERSION=$version" >> "$GITHUB_ENV"
        sed -i \
          "s/^version =\".*\"/version =\"${version}\"/" \
          pyproject.toml
            
    - name: Build Windows binary
      run: |
        docker run -v ${{github.workspace}}:/src \
         -e PIP_GROUPS=windows,develop \
         -e SPECFILE=scripts/windows/papis.spec \
         ghcr.io/kiike/pyinstaller-windows:latest
    
    - name: Publish binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: papis-${{env.PAPIS_VERSION}}
        path: ${{ github.workspace }}/dist/papis.exe
